live_config_reload = true

[window]
dynamic_padding = true
dynamic_title = true
dimensions = { columns = 120, lines = 36 }

[scrolling]
history = 20000
multiplier = 3

[env]
TERM = "xterm-256color"

[font]
size = 14.0
bold = { family = "JetBrains Mono", style = "ExtraBold" }
bold_italic = { family = "JetBrains Mono", style = "ExtraBold Italic" }
italic = { family = "JetBrains Mono", style = "Italic" }
normal = { family = "JetBrains Mono", style = "Regular" }

[cursor]
thickness = 0.15
unfocused_hollow = true

[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = [
    { index = 16, color = "0xffa066" },
    { index = 17, color = "0xff5d62" }
]

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[keyboard]
bindings = [
    { action = "SpawnNewInstance", key = "N", mods = "Control|Shift" },
    { action = "Quit", key = "Q", mods = "Alt" },
]

[mouse]
hide_when_typing = true
